services:
  auth:
    build:
      context: ./src/auth_service
      dockerfile: Dockerfile
    ports:
      - '5000:443'
    volumes:
      - ./ca.key:/app/ca.key
      - ./ca.crt:/app/ca.crt

  orders:
    build:
      context: ./src/orders_service
      dockerfile: Dockerfile
    ports:
      - '5001:443'
    volumes:
      - ./ca.key:/app/ca.key
      - ./ca.crt:/app/ca.crt
